### ISSUE TITLE
有几个问题请教

### ISSUE THREAD

**Issue by acetao** [wilsonjuxta/sdibtoj#2]
（1）自己采用hustoj搭建了一个oj，现在看到您做的exam不错，想把exam加到oj里面去。但又想使用hustoj的前台，不想使用您的前台，只是想把exam作为插件加进去。按照您说的“安装方法，直接将web/stuexam放在本地JudgeOnline/web/目录下即可，并把数据表添加到原先oj的jol后”，不能正确运行。
http://localhost/JudgeOnline/stuexam无显示，http://localhost/JudgeOnline/web/stuexam无法读取数据库里面的内容。我确信更改了db_info.inc.php里面的数据库配置。
（2）sdibtoj目录下有一个stuexam目录，然后在web目录下又有一个stuexam目录，而且这2个目录的内容还不相同，使用哪个？还是2个都使用？
（3）web目录下除了stuexam目录外，还有其他目录和文件，好像和sdibtoj目录下的文件内容都相同。困惑了。
（4）以上问题，如果使用您的前台，没有问题。但是我还是想使用hustoj的前台，因为自己也是对其进行了一定的修改，想保持下去。
希望能拨冗解答这些问题，谢谢！

**Comment by wilsonjuxta** [comment]
不好意思，现在才回复～
首先谢谢关注。

我把exam部分重新写了一遍，如今跟原先的hustoj关联性不是很大了，
只有几部分关联：数据库的共同使用。对于原oj的其他方面都不会受到影响。
很抱歉的是，这个目录一开始只是为了保存使用，所以没有进行相应的整合，从而 
造成了重复
我会尽快更新最新的版本。

新版的exam部分也同样需要配置数据库的基本信息，这个我会写在readme当中，十 
分抱歉。

另外，现在的exam部分还没有开发完成，像tags的一些功能还不够完善。但基本可 
以使用了。





于 03/28/2015 11:05 PM, acetao 写道:

**Comment by acetao** [comment]
谢谢您的回复，我也在看源码，找问题，希望能把它们整合起来，然后用到教学之中。
会一直关注下去。
