### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by acetao** [wilsonjuxta/sdibtoj#3]
按照安装说明，将stuexam拷贝到了JudgeOnline目录下，进行了相应的设置，也修改了权限；导入了exam.sql脚本到jol中；也分别对Index/Common/Config目录、Index/Home/Config目录、Index/Teacher/Config目录下的参数进行了修改，主要是修改了数据库登录密码，其它未有修改；
然后：
http://localhost/JudgeOnline/stuexam/ 这个链接正常；
但是该页面中的“教师管理”链接：http://localhost/JudgeOnline/stuexam/Teacher/Index/index
和“Exam List”链接：http://localhost/JudgeOnline/stuexam/Home/Index/index
却不能正常显示（你访问的网页不存在），不知道是什么原因？
烦请拨冗释疑，谢谢！

**Comment by wilsonjuxta** [comment]
你是否对apache配置文件进行设置？需要设置url重写。可以直接email联系。。方便点。。

**Comment by acetao** [comment]
我的email是acetao@163.com
